### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Emmo00** [ndurumo254/ndurumo254.github.io#1]
I noticed that in your description with the typing effect, you used "I'm a Electrical..." Instead of "I'm an Electrical..."👍
![Screenshot_20230518_205322 (1)](https://github.com/ndurumo254/ndurumo254.github.io/assets/88244468/18e44388-263c-4bf4-a660-642426153096)

**Comment by erick1muriuki** [comment]
ooh, thanks for that am going to make some changes.
